export type Font = {
  slug: string;
  family: string;
  designer: string;
  category: string;
  tags: string[];
  scripts: string[];
  weights: number[];
  variable: boolean;
  styles: string[];
  license: string;
  licenseUrl: string;
  sourceUrl: string;
  googleFamily: string;
  description: string;
};

const g = (family: string) => encodeURIComponent(family).replace(/%20/g, "+");

export const fonts: Font[] = [
  { slug:"inter", family:"Inter", designer:"Rasmus Andersson", category:"Sans Serif", tags:["modern","clean","ui","professional"], scripts:["Latin","Greek","Cyrillic"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Inter", googleFamily:g("Inter"), description:"A clean, versatile typeface designed for screens and interfaces." },
  { slug:"roboto", family:"Roboto", designer:"Christian Robertson", category:"Sans Serif", tags:["neutral","ui","android","modern"], scripts:["Latin","Greek","Cyrillic"], weights:[100,300,400,500,700,900], variable:true, styles:["normal","italic"], license:"Apache License 2.0", licenseUrl:"https://www.apache.org/licenses/LICENSE-2.0", sourceUrl:"https://fonts.google.com/specimen/Roboto", googleFamily:g("Roboto"), description:"A highly readable neo-grotesque sans serif for interfaces and products." },
  { slug:"poppins", family:"Poppins", designer:"Indian Type Foundry", category:"Sans Serif", tags:["geometric","friendly","modern","rounded"], scripts:["Latin","Devanagari"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Poppins", googleFamily:g("Poppins"), description:"A geometric sans with a distinctive circular construction." },
  { slug:"montserrat", family:"Montserrat", designer:"Julieta Ulanovsky", category:"Sans Serif", tags:["geometric","bold","branding","display"], scripts:["Latin","Cyrillic","Vietnamese"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Montserrat", googleFamily:g("Montserrat"), description:"A contemporary geometric sans inspired by urban lettering." },
  { slug:"manrope", family:"Manrope", designer:"Michael Sharanda", category:"Sans Serif", tags:["minimal","modern","ui","soft"], scripts:["Latin","Cyrillic","Greek"], weights:[200,300,400,500,600,700,800], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Manrope", googleFamily:g("Manrope"), description:"A modern geometric grotesque with a soft, contemporary character." },
  { slug:"dm-sans", family:"DM Sans", designer:"Colophon Foundry", category:"Sans Serif", tags:["clean","ui","friendly","variable"], scripts:["Latin","Greek","Cyrillic"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/DM+Sans", googleFamily:g("DM Sans"), description:"A low-contrast geometric sans designed for interface text." },
  { slug:"outfit", family:"Outfit", designer:"Onlook", category:"Sans Serif", tags:["modern","geometric","display","startup"], scripts:["Latin","Vietnamese"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Outfit", googleFamily:g("Outfit"), description:"A geometric sans with expressive forms for interfaces and headlines." },
  { slug:"plus-jakarta-sans", family:"Plus Jakarta Sans", designer:"Tokotype", category:"Sans Serif", tags:["premium","ui","modern","editorial"], scripts:["Latin","Arabic","Vietnamese"], weights:[200,300,400,500,600,700,800], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Plus+Jakarta+Sans", googleFamily:g("Plus Jakarta Sans"), description:"A contemporary sans family with broad language support." },
  { slug:"lato", family:"Lato", designer:"Łukasz Dziedzic", category:"Sans Serif", tags:["humanist","professional","readable"], scripts:["Latin","Greek","Cyrillic"], weights:[100,300,400,700,900], variable:false, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Lato", googleFamily:g("Lato"), description:"A humanist sans balancing warmth with a serious professional feel." },
  { slug:"nunito-sans", family:"Nunito Sans", designer:"Vernon Adams", category:"Sans Serif", tags:["rounded","friendly","ui","soft"], scripts:["Latin","Greek","Cyrillic"], weights:[200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Nunito+Sans", googleFamily:g("Nunito Sans"), description:"A rounded humanist sans suited to friendly interfaces." },
  { slug:"open-sans", family:"Open Sans", designer:"Steve Matteson", category:"Sans Serif", tags:["readable","ui","classic","neutral"], scripts:["Latin","Greek","Cyrillic"], weights:[300,400,500,600,700,800], variable:true, styles:["normal","italic"], license:"Apache License 2.0", licenseUrl:"https://www.apache.org/licenses/LICENSE-2.0", sourceUrl:"https://fonts.google.com/specimen/Open+Sans", googleFamily:g("Open Sans"), description:"A humanist sans optimized for legibility across interfaces and documents." },
  { slug:"source-sans-3", family:"Source Sans 3", designer:"Paul D. Hunt", category:"Sans Serif", tags:["editorial","ui","readable","open source"], scripts:["Latin","Greek","Cyrillic"], weights:[200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Source+Sans+3", googleFamily:g("Source Sans 3"), description:"Adobe's open-source sans family built for text-heavy interfaces." },
  { slug:"geist", family:"Geist", designer:"Vercel", category:"Sans Serif", tags:["minimal","ui","developer","modern"], scripts:["Latin","Greek","Cyrillic"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://vercel.com/font", googleFamily:g("Geist"), description:"A crisp sans designed for modern software interfaces." },
  { slug:"archivo", family:"Archivo", designer:"Omse", category:"Sans Serif", tags:["grotesk","business","ui","variable"], scripts:["Latin","Greek","Cyrillic"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Archivo", googleFamily:g("Archivo"), description:"A grotesque sans with a strong utility-oriented character." },
  { slug:"rubik", family:"Rubik", designer:"Philipp Hubert", category:"Sans Serif", tags:["rounded","friendly","modern","ui"], scripts:["Latin","Cyrillic","Hebrew"], weights:[300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Rubik", googleFamily:g("Rubik"), description:"A rounded sans with subtly rounded corners and approachable forms." },
  { slug:"work-sans", family:"Work Sans", designer:"Wei Huang", category:"Sans Serif", tags:["workhorse","ui","neutral","readable"], scripts:["Latin","Greek","Cyrillic"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Work+Sans", googleFamily:g("Work Sans"), description:"A versatile sans tuned for medium-sized text and UI work." },
  { slug:"roboto-slab", family:"Roboto Slab", designer:"Christian Robertson", category:"Slab Serif", tags:["slab","ui","editorial","robust"], scripts:["Latin","Greek","Cyrillic"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"Apache License 2.0", licenseUrl:"https://www.apache.org/licenses/LICENSE-2.0", sourceUrl:"https://fonts.google.com/specimen/Roboto+Slab", googleFamily:g("Roboto Slab"), description:"A sturdy slab serif that works well for headings and interfaces." },
  { slug:"playfair-display", family:"Playfair Display", designer:"Claus Eggers Sørensen", category:"Serif", tags:["editorial","elegant","luxury","display"], scripts:["Latin","Cyrillic","Vietnamese"], weights:[400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Playfair+Display", googleFamily:g("Playfair Display"), description:"A high-contrast transitional serif designed for large display text." },
  { slug:"merriweather", family:"Merriweather", designer:"Eben Sorkin", category:"Serif", tags:["reading","editorial","classic","book"], scripts:["Latin","Cyrillic","Vietnamese"], weights:[300,400,700,900], variable:false, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Merriweather", googleFamily:g("Merriweather"), description:"A sturdy serif designed for comfortable reading on screens." },
  { slug:"libre-baskerville", family:"Libre Baskerville", designer:"Impallari Type", category:"Serif", tags:["book","classic","editorial","reading"], scripts:["Latin"], weights:[400,700], variable:false, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Libre+Baskerville", googleFamily:g("Libre Baskerville"), description:"A web-optimized revival of the classic Baskerville style." },
  { slug:"lora", family:"Lora", designer:"Cyreal", category:"Serif", tags:["editorial","calligraphic","reading"], scripts:["Latin","Cyrillic","Vietnamese"], weights:[400,500,600,700], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Lora", googleFamily:g("Lora"), description:"A contemporary serif with calligraphic roots and strong reading texture." },
  { slug:"cormorant-garamond", family:"Cormorant Garamond", designer:"Christian Thalmann", category:"Serif", tags:["fashion","elegant","editorial","high contrast"], scripts:["Latin","Cyrillic","Vietnamese"], weights:[300,400,500,600,700], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Cormorant+Garamond", googleFamily:g("Cormorant Garamond"), description:"An elegant display-oriented Garamond interpretation with expressive contrast." },
  { slug:"bitter", family:"Bitter", designer:"Sol Matas", category:"Slab Serif", tags:["slab","reading","friendly","editorial"], scripts:["Latin","Greek","Cyrillic"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Bitter", googleFamily:g("Bitter"), description:"A robust slab serif designed for digital reading." },
  { slug:"dm-mono", family:"DM Mono", designer:"Colophon Foundry", category:"Monospace", tags:["code","developer","terminal","technical"], scripts:["Latin","Greek","Cyrillic"], weights:[300,400,500], variable:false, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/DM+Mono", googleFamily:g("DM Mono"), description:"A compact monospaced family designed for code and technical UI." },
  { slug:"jetbrains-mono", family:"JetBrains Mono", designer:"Philipp Nurullin", category:"Monospace", tags:["code","developer","ligatures","terminal"], scripts:["Latin","Cyrillic","Greek","Hebrew"], weights:[100,200,300,400,500,600,700,800], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/JetBrains+Mono", googleFamily:g("JetBrains Mono"), description:"A developer-focused monospace with increased character width for code readability." },
  { slug:"fira-code", family:"Fira Code", designer:"Nikita Prokopov", category:"Monospace", tags:["code","ligatures","developer","programming"], scripts:["Latin","Cyrillic","Greek"], weights:[300,400,500,600,700], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Fira+Code", googleFamily:g("Fira Code"), description:"A programming typeface with common multi-character programming ligatures." },
  { slug:"space-mono", family:"Space Mono", designer:"Colophon Foundry", category:"Monospace", tags:["technical","retro","code","display"], scripts:["Latin","Greek","Cyrillic"], weights:[400,700], variable:false, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Space+Mono", googleFamily:g("Space Mono"), description:"A distinctive fixed-width family with a technical editorial voice." },
  { slug:"orbitron", family:"Orbitron", designer:"Matt McInerney", category:"Display", tags:["futuristic","tech","geometric","display"], scripts:["Latin"], weights:[400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Orbitron", googleFamily:g("Orbitron"), description:"A geometric display face inspired by technology and science fiction." },
  { slug:"bebas-neue", family:"Bebas Neue", designer:"Ryoichi Tsunekawa", category:"Display", tags:["condensed","poster","branding","bold"], scripts:["Latin"], weights:[400], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Bebas+Neue", googleFamily:g("Bebas Neue"), description:"A condensed all-caps display face suited to posters and headlines." },
  { slug:"anton", family:"Anton", designer:"Vernon Adams", category:"Display", tags:["bold","condensed","headline","poster"], scripts:["Latin","Vietnamese"], weights:[400], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Anton", googleFamily:g("Anton"), description:"A bold grotesque display face built for strong headlines." },
  { slug:"oswald", family:"Oswald", designer:"Vernon Adams", category:"Display", tags:["condensed","headline","editorial","bold"], scripts:["Latin","Cyrillic","Vietnamese"], weights:[200,300,400,500,600,700], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Oswald", googleFamily:g("Oswald"), description:"A reworking of classic gothic and grotesque typefaces for digital use." },
  { slug:"archivo-black", family:"Archivo Black", designer:"Omse", category:"Display", tags:["heavy","branding","poster","bold"], scripts:["Latin"], weights:[400], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Archivo+Black", googleFamily:g("Archivo Black"), description:"An ultra-heavy grotesque for high-impact display typography." },
  { slug:"pacifico", family:"Pacifico", designer:"Vernon Adams", category:"Script", tags:["retro","handwritten","friendly","display"], scripts:["Latin","Cyrillic","Greek"], weights:[400], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Pacifico", googleFamily:g("Pacifico"), description:"A playful brush script with a relaxed, hand-lettered character." },
  { slug:"great-vibes", family:"Great Vibes", designer:"Robert E. Leuschke", category:"Script", tags:["calligraphy","wedding","elegant","handwriting"], scripts:["Latin"], weights:[400], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Great+Vibes", googleFamily:g("Great Vibes"), description:"A flowing formal script with connected calligraphic forms." },
  { slug:"caveat", family:"Caveat", designer:"Pablo Impallari", category:"Handwriting", tags:["handwritten","casual","notes","friendly"], scripts:["Latin","Cyrillic"], weights:[400,500,600,700], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Caveat", googleFamily:g("Caveat"), description:"A casual handwriting style suitable for annotations and personal notes." },
  { slug:"dancing-script", family:"Dancing Script", designer:"Impallari Type", category:"Handwriting", tags:["handwritten","casual","friendly","script"], scripts:["Latin","Vietnamese"], weights:[400,500,600,700], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Dancing+Script", googleFamily:g("Dancing Script"), description:"A lively handwritten script with an informal, personal rhythm." },
  { slug:"permanent-marker", family:"Permanent Marker", designer:"Font Diner", category:"Handwriting", tags:["marker","bold","poster","casual"], scripts:["Latin"], weights:[400], variable:false, styles:["normal"], license:"Apache License 2.0", licenseUrl:"https://www.apache.org/licenses/LICENSE-2.0", sourceUrl:"https://fonts.google.com/specimen/Permanent+Marker", googleFamily:g("Permanent Marker"), description:"A bold marker-style handwriting face with a casual poster feel." },
  { slug:"press-start-2p", family:"Press Start 2P", designer:"CodeMan38", category:"Pixel", tags:["pixel","retro","game","arcade"], scripts:["Latin","Cyrillic","Greek"], weights:[400], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Press+Start+2P", googleFamily:g("Press Start 2P"), description:"A bitmap-inspired display face referencing classic arcade games." },
  { slug:"silkscreen", family:"Silkscreen", designer:"Jason Kottke", category:"Pixel", tags:["pixel","bitmap","retro","ui"], scripts:["Latin"], weights:[400,700], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Silkscreen", googleFamily:g("Silkscreen"), description:"A compact pixel display face designed for digital interfaces." },
  { slug:"unifrakturcook", family:"UnifrakturCook", designer:"Jörg Petri", category:"Blackletter", tags:["blackletter","gothic","historical","display"], scripts:["Latin"], weights:[400,700], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/UnifrakturCook", googleFamily:g("UnifrakturCook"), description:"A blackletter display face with traditional gothic forms." },
  { slug:"comfortaa", family:"Comfortaa", designer:"Johan Aakerlund", category:"Sans Serif", tags:["rounded","friendly","display","soft"], scripts:["Latin","Cyrillic","Greek","Vietnamese"], weights:[300,400,500,600,700], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Comfortaa", googleFamily:g("Comfortaa"), description:"A rounded geometric face with a soft, friendly personality." },
  { slug:"alfa-slab-one", family:"Alfa Slab One", designer:"JM Solé", category:"Slab Serif", tags:["slab","display","bold","retro"], scripts:["Latin","Vietnamese"], weights:[400], variable:false, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Alfa+Slab+One", googleFamily:g("Alfa Slab One"), description:"A heavy slab serif with a strong poster and advertising character." },
  { slug:"archivo-narrow", family:"Archivo Narrow", designer:"Omse", category:"Sans Serif", tags:["narrow","compact","ui","editorial"], scripts:["Latin","Greek","Cyrillic"], weights:[400,500,600,700], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Archivo+Narrow", googleFamily:g("Archivo Narrow"), description:"A narrow grotesque optimized for compact layouts and headlines." },
  { slug:"noto-sans-malayalam", family:"Noto Sans Malayalam", designer:"Google", category:"Sans Serif", tags:["malayalam","multilingual","ui","unicode"], scripts:["Malayalam"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Noto+Sans+Malayalam", googleFamily:g("Noto Sans Malayalam"), description:"A Malayalam sans-serif family from the Noto collection." },
  { slug:"noto-serif-malayalam", family:"Noto Serif Malayalam", designer:"Google", category:"Serif", tags:["malayalam","multilingual","editorial","unicode"], scripts:["Malayalam"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Noto+Serif+Malayalam", googleFamily:g("Noto Serif Malayalam"), description:"A Malayalam serif family for reading and editorial layouts." },
  { slug:"noto-sans-devanagari", family:"Noto Sans Devanagari", designer:"Google", category:"Sans Serif", tags:["devanagari","multilingual","unicode","ui"], scripts:["Devanagari"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Noto+Sans+Devanagari", googleFamily:g("Noto Sans Devanagari"), description:"A Devanagari sans-serif family in the Noto collection." },
  { slug:"noto-sans-tamil", family:"Noto Sans Tamil", designer:"Google", category:"Sans Serif", tags:["tamil","multilingual","unicode","ui"], scripts:["Tamil"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Noto+Sans+Tamil", googleFamily:g("Noto Sans Tamil"), description:"A Tamil sans-serif family designed for broad Unicode coverage." },
  { slug:"noto-sans-kannada", family:"Noto Sans Kannada", designer:"Google", category:"Sans Serif", tags:["kannada","multilingual","unicode","ui"], scripts:["Kannada"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Noto+Sans+Kannada", googleFamily:g("Noto Sans Kannada"), description:"A Kannada sans-serif family from the Noto collection." },
  { slug:"noto-sans-telugu", family:"Noto Sans Telugu", designer:"Google", category:"Sans Serif", tags:["telugu","multilingual","unicode","ui"], scripts:["Telugu"], weights:[100,200,300,400,500,600,700,800,900], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Noto+Sans+Telugu", googleFamily:g("Noto Sans Telugu"), description:"A Telugu sans-serif family from the Noto collection." },
  { slug:"ibm-plex-sans", family:"IBM Plex Sans", designer:"Mike Abbink", category:"Sans Serif", tags:["corporate","technical","ui","professional"], scripts:["Latin","Greek","Cyrillic","Arabic","Hebrew"], weights:[100,200,300,400,500,600,700], variable:false, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/IBM+Plex+Sans", googleFamily:g("IBM Plex Sans"), description:"A corporate type family designed for clarity across technical contexts." },
  { slug:"source-code-pro", family:"Source Code Pro", designer:"Paul D. Hunt", category:"Monospace", tags:["code","developer","terminal","adobe"], scripts:["Latin","Greek","Cyrillic"], weights:[200,300,400,500,600,700,800,900], variable:true, styles:["normal","italic"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Source+Code+Pro", googleFamily:g("Source Code Pro"), description:"Adobe's open-source monospaced typeface for coding environments." },
  { slug:"quicksand", family:"Quicksand", designer:"Andrew Paglinawan", category:"Sans Serif", tags:["rounded","friendly","geometric","display"], scripts:["Latin","Vietnamese"], weights:[300,400,500,600,700], variable:true, styles:["normal"], license:"SIL Open Font License 1.1", licenseUrl:"https://scripts.sil.org/OFL", sourceUrl:"https://fonts.google.com/specimen/Quicksand", googleFamily:g("Quicksand"), description:"A rounded geometric sans with a light, approachable feel." }
];

export const categories = ["Sans Serif","Serif","Slab Serif","Monospace","Display","Handwriting","Script","Blackletter","Pixel"];
export const scripts = ["Latin","Greek","Cyrillic","Arabic","Hebrew","Devanagari","Bengali","Gujarati","Gurmukhi","Kannada","Malayalam","Tamil","Telugu","Thai","Georgian","Armenian"];

export function getFont(slug: string) { return fonts.find((f) => f.slug === slug); }

export function googleCssUrl(font: Font, weights?: number[]) {
  const selected = weights?.length ? weights : font.weights;
  const unique = [...new Set(selected)].sort((a,b)=>a-b);
  const axis = unique.join(";");
  const family = font.googleFamily;
  return `https://fonts.googleapis.com/css2?family=${family}:wght@${axis}&display=swap`;
}
